[Feature](bangpy-ops): add pylint check into pre-commit check. (#38)

diff --git a/tools/pre-commit b/tools/pre-commit
--- a/tools/pre-commit
+++ b/tools/pre-commit
@@ -127,4 +127,27 @@ else
   echo "-- [pre-commit] check printf PASSED."
 fi
 
+if [[ "$(which pylint)" == "" ]]; then
+  echo "Please pip install pylint!(pylint==2.9)"
+  exit -1
+fi
+
+echo "-- [pre-commit] Using pylint to check bangpy/ops \
+by .git/hooks/pre-commit..."
+python3 -m pylint ./bangpy-ops --rcfile=./bangpy-ops/utils/pylintrc 2>&1 \
+     | grep -v "Your code" \
+     | grep -v "Module bangpy" \
+     | grep -E ".py"
+
+if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
+  ret=1
+fi
+
+if [[ ${ret} != 0 ]]; then
+  echo "-- [pre-commit] pylint FAILED: Please fix pylint errors."
+  exit ${ret}
+else
+  echo "-- [pre-commit] pylint PASSED."
+fi
+
 exit 0
